### ISSUE TITLE
Account deletion flow is not themed

### ISSUE THREAD

**Issue by doamatto** [BlueJayOne/bluejay#11]
**Describe the bug**
The model and notification does not get properly themed when the user is using dar theme system-wide.

**To Reproduce**
1. Try deleting your account in `/app/settings`
2. See a light themed model and notification if you do delete your account.

**Expected behavior**
The model and notification should be under the same theming of the site

**Screenshots**
![image](https://user-images.githubusercontent.com/30969346/128587205-c90af867-03ef-4f16-985e-0755acd139d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 E-Channel
 - Browser: Chromium/Edge
 - Version: 92.0.902.62

**Comment by tessamerrill** [comment]
Fixed in https://github.com/BlueJayOne/web/commit/a9f2b2416890f2e42f536c571d524912381e9f3c
