### ISSUE TITLE
Cookies and local storage persists after account deletion

### ISSUE THREAD

**Issue by doamatto** [BlueJayOne/bluejay#12]
**Describe the bug**
When a user deletes their account, both cookies and local storage persists

**To Reproduce**
1. Delete your account with the `/app/settings` flow
2. Check your cookies and storage with Chrome DevTools or a similar utility
3. Notice that the `nextauth.message` local storage and the `__Host-next-auth.csrf-token` cookie persists.

**Expected behavior**
Both cookies and local storage should be cleared to give a true New User experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/30969346/128587344-71ff7a57-df94-45a8-8390-3d275580add2.png)
![image](https://user-images.githubusercontent.com/30969346/128587341-27526274-7992-4262-a5df-ffd4e1c6e069.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 E-Channel
 - Browser: Chromium/Edge
 - Version: 92.0.902.62

**Comment by tessamerrill** [comment]
Fixed in https://github.com/BlueJayOne/web/commit/a9f2b2416890f2e42f536c571d524912381e9f3c
