### ISSUE TITLE
User can bypass age restriction by going to homepage.

### ISSUE THREAD

**Issue by tessamerrill** [BlueJayOne/bluejay#13]
**Describe the bug**
Self explanatory.

**To Reproduce**
1. Create new account
2. When at age checker, go to homepage
3. Go to /app

**Expected behavior**
Show age checker page

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] i don't know lmao

**Comment by doamatto** [comment]
> Version [e.g. 22] i don't know lmao

https://support.mozilla.org/en-US/kb/find-what-version-firefox-you-are-using.

Answer: probably latest; 90.0.2

**Comment by tessamerrill** [comment]
Fixed in https://github.com/BlueJayOne/web/commit/f00cb6914b2854c5b53b72886715bdfb7058f97e
