### ISSUE TITLE
Unauthed pages flashes as authed before moving to login

### ISSUE THREAD

**Issue by doamatto** [BlueJayOne/bluejay#14]
**Describe the bug**
When you go to an unauthorised page (while logged out, for instance), you will see that page for a second or so, before being redirected. It would be ideal to prevent that page from loading in the first place, as the user is not authenticated.

**To Reproduce**
1. Go to a page while authorised to verify it loads
2. Logout of BlueJay
3. Go to the page from before while logged out
4. A flash of a logged in view will appear, followed by the login screen

**Expected behavior**
It should go straight to the login page, rather than flash other content first

**Desktop (please complete the following information):**
 - OS: Windows 10 E-Channel
 - Browser: Chromium/Edge
 - Version: 92.0.902.62

**Additional context**
Untested on mobile, as of writing. Will test when I get a chance.

**Comment by tessamerrill** [comment]
Due to the method that SWR (next-auth) uses to check if the user is authenticated, this may not be fixable. Only way to fix this issue is if I moved to server-side rendering, or to show a blank screen until the user is checked.

**Comment by doamatto** [comment]
> or to show a blank screen until the user is checked.

You should be able to show a loading screen interim, rather than a blank screen.
